// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_ark_groth16`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2026-01-24, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ggwpez-ref-hw2`, CPU: `AMD EPYC 7232P 8-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// ./target/release/ark-node
// benchmark
// pallet
// --runtime=target/release/wbuild/ark-runtime/ark_runtime.compact.wasm
// --template=pallets/frame-weight-template.hbs
// --pallet
// pallet_ark_groth16
// --extrinsic
// *
// --steps
// 50
// --repeat=20
// --no-storage-info
// --disable-proof-recording
// --no-median-slopes
// --json-file=./pallets/groth16/src/results.json
// --output=./pallets/groth16/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_ark_groth16`.
pub trait WeightInfo {
	fn ark_bls12_381_groth16_verify() -> Weight;
	fn sub_bls12_381_groth16_verify() -> Weight;
	fn ark_bls12_377_groth16_verify() -> Weight;
	fn sub_bls12_377_groth16_verify() -> Weight;
	fn ark_bw6_761_groth16_verify() -> Weight;
	fn sub_bw6_761_groth16_verify() -> Weight;
}

/// Weights for `pallet_ark_groth16` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn ark_bls12_381_groth16_verify() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 21_103_068_000 picoseconds.
		Weight::from_parts(21_135_129_000, 0)
	}
	fn sub_bls12_381_groth16_verify() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_552_928_000 picoseconds.
		Weight::from_parts(3_559_599_000, 0)
	}
	fn ark_bls12_377_groth16_verify() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 22_325_178_000 picoseconds.
		Weight::from_parts(22_348_929_000, 0)
	}
	fn sub_bls12_377_groth16_verify() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_852_271_000 picoseconds.
		Weight::from_parts(3_862_840_000, 0)
	}
	fn ark_bw6_761_groth16_verify() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 109_186_813_000 picoseconds.
		Weight::from_parts(109_252_043_000, 0)
	}
	fn sub_bw6_761_groth16_verify() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 13_123_824_000 picoseconds.
		Weight::from_parts(13_143_284_000, 0)
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	fn ark_bls12_381_groth16_verify() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 21_103_068_000 picoseconds.
		Weight::from_parts(21_135_129_000, 0)
	}
	fn sub_bls12_381_groth16_verify() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_552_928_000 picoseconds.
		Weight::from_parts(3_559_599_000, 0)
	}
	fn ark_bls12_377_groth16_verify() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 22_325_178_000 picoseconds.
		Weight::from_parts(22_348_929_000, 0)
	}
	fn sub_bls12_377_groth16_verify() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_852_271_000 picoseconds.
		Weight::from_parts(3_862_840_000, 0)
	}
	fn ark_bw6_761_groth16_verify() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 109_186_813_000 picoseconds.
		Weight::from_parts(109_252_043_000, 0)
	}
	fn sub_bw6_761_groth16_verify() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 13_123_824_000 picoseconds.
		Weight::from_parts(13_143_284_000, 0)
	}
}
