// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_ark_vrf`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2026-01-24, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ggwpez-ref-hw2`, CPU: `AMD EPYC 7232P 8-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// ./target/release/ark-node
// benchmark
// pallet
// --runtime=target/release/wbuild/ark-runtime/ark_runtime.compact.wasm
// --template=pallets/frame-weight-template.hbs
// --pallet
// pallet_ark_vrf
// --extrinsic
// *
// --steps
// 50
// --repeat=20
// --no-storage-info
// --disable-proof-recording
// --no-median-slopes
// --json-file=./pallets/vrf/src/results.json
// --output=./pallets/vrf/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_ark_vrf`.
pub trait WeightInfo {
	fn ark_ring_vrf_commit_buffered(x: u32, ) -> Weight;
	fn sub_ring_vrf_commit_buffered(x: u32, ) -> Weight;
	fn ark_ring_vrf_commit_unbuffered(x: u32, ) -> Weight;
	fn sub_ring_vrf_commit_unbuffered(x: u32, ) -> Weight;
	fn ark_ring_vrf_verify(x: u32, ) -> Weight;
	fn sub_ring_vrf_verify(x: u32, ) -> Weight;
	fn ark_ietf_vrf_verify() -> Weight;
	fn sub_ietf_vrf_verify() -> Weight;
}

/// Weights for `pallet_ark_vrf` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `ArkVrf::RingKeys` (r:1 w:0)
	/// Proof: `ArkVrf::RingKeys` (`max_values`: Some(1), `max_size`: Some(8162), added: 8657, mode: `MaxEncodedLen`)
	/// Storage: `ArkVrf::RingSize` (r:1 w:1)
	/// Proof: `ArkVrf::RingSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ArkVrf::RingBuilder` (r:1 w:1)
	/// Proof: `ArkVrf::RingBuilder` (`max_values`: Some(1), `max_size`: Some(848), added: 1343, mode: `MaxEncodedLen`)
	/// Storage: `ArkVrf::Srs` (r:7 w:0)
	/// Proof: `ArkVrf::Srs` (`max_values`: None, `max_size`: Some(396), added: 2871, mode: `MaxEncodedLen`)
	/// Storage: `ArkVrf::RingVerifierKey` (r:0 w:1)
	/// Proof: `ArkVrf::RingVerifierKey` (`max_values`: Some(1), `max_size`: Some(384), added: 879, mode: `MaxEncodedLen`)
	/// The range of component `x` is `[1, 50]`.
	fn ark_ring_vrf_commit_buffered(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1808 + x * (87 ±0)`
		//  Estimated: `9647 + x * (355 ±2)`
		// Minimum execution time: 4_894_579_000 picoseconds.
		Weight::from_parts(4_294_985_512, 9647)
			// Standard Error: 4_456_518
			.saturating_add(Weight::from_parts(1_574_884_572, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 355).saturating_mul(x.into()))
	}
	/// Storage: `ArkVrf::RingKeys` (r:1 w:0)
	/// Proof: `ArkVrf::RingKeys` (`max_values`: Some(1), `max_size`: Some(8162), added: 8657, mode: `MaxEncodedLen`)
	/// Storage: `ArkVrf::RingSize` (r:1 w:1)
	/// Proof: `ArkVrf::RingSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ArkVrf::RingBuilder` (r:1 w:1)
	/// Proof: `ArkVrf::RingBuilder` (`max_values`: Some(1), `max_size`: Some(848), added: 1343, mode: `MaxEncodedLen`)
	/// Storage: `ArkVrf::Srs` (r:7 w:0)
	/// Proof: `ArkVrf::Srs` (`max_values`: None, `max_size`: Some(396), added: 2871, mode: `MaxEncodedLen`)
	/// Storage: `ArkVrf::RingVerifierKey` (r:0 w:1)
	/// Proof: `ArkVrf::RingVerifierKey` (`max_values`: Some(1), `max_size`: Some(384), added: 879, mode: `MaxEncodedLen`)
	/// The range of component `x` is `[1, 50]`.
	fn sub_ring_vrf_commit_buffered(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1808 + x * (87 ±0)`
		//  Estimated: `9647 + x * (355 ±2)`
		// Minimum execution time: 1_325_625_000 picoseconds.
		Weight::from_parts(1_070_210_802, 9647)
			// Standard Error: 319_246
			.saturating_add(Weight::from_parts(459_294_054, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 355).saturating_mul(x.into()))
	}
	/// Storage: `ArkVrf::RingKeys` (r:1 w:0)
	/// Proof: `ArkVrf::RingKeys` (`max_values`: Some(1), `max_size`: Some(8162), added: 8657, mode: `MaxEncodedLen`)
	/// Storage: `ArkVrf::RingBuilder` (r:1 w:0)
	/// Proof: `ArkVrf::RingBuilder` (`max_values`: Some(1), `max_size`: Some(848), added: 1343, mode: `MaxEncodedLen`)
	/// Storage: `ArkVrf::RingVerifierKey` (r:0 w:1)
	/// Proof: `ArkVrf::RingVerifierKey` (`max_values`: Some(1), `max_size`: Some(384), added: 879, mode: `MaxEncodedLen`)
	/// The range of component `x` is `[1, 50]`.
	fn ark_ring_vrf_commit_unbuffered(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `940`
		//  Estimated: `9647`
		// Minimum execution time: 28_560_000 picoseconds.
		Weight::from_parts(29_212_681, 9647)
			// Standard Error: 724
			.saturating_add(Weight::from_parts(23_986, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `ArkVrf::RingKeys` (r:1 w:0)
	/// Proof: `ArkVrf::RingKeys` (`max_values`: Some(1), `max_size`: Some(8162), added: 8657, mode: `MaxEncodedLen`)
	/// Storage: `ArkVrf::RingBuilder` (r:1 w:0)
	/// Proof: `ArkVrf::RingBuilder` (`max_values`: Some(1), `max_size`: Some(848), added: 1343, mode: `MaxEncodedLen`)
	/// Storage: `ArkVrf::RingVerifierKey` (r:0 w:1)
	/// Proof: `ArkVrf::RingVerifierKey` (`max_values`: Some(1), `max_size`: Some(384), added: 879, mode: `MaxEncodedLen`)
	/// The range of component `x` is `[1, 50]`.
	fn sub_ring_vrf_commit_unbuffered(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `940`
		//  Estimated: `9647`
		// Minimum execution time: 50_911_000 picoseconds.
		Weight::from_parts(51_722_907, 9647)
			// Standard Error: 1_662
			.saturating_add(Weight::from_parts(35_199, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `ArkVrf::RingVerifierKey` (r:1 w:0)
	/// Proof: `ArkVrf::RingVerifierKey` (`max_values`: Some(1), `max_size`: Some(384), added: 879, mode: `MaxEncodedLen`)
	/// The range of component `x` is `[1, 50]`.
	fn ark_ring_vrf_verify(_x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `489`
		//  Estimated: `1869`
		// Minimum execution time: 40_654_535_000 picoseconds.
		Weight::from_parts(41_032_265_431, 1869)
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
	/// Storage: `ArkVrf::RingVerifierKey` (r:1 w:0)
	/// Proof: `ArkVrf::RingVerifierKey` (`max_values`: Some(1), `max_size`: Some(384), added: 879, mode: `MaxEncodedLen`)
	/// The range of component `x` is `[1, 50]`.
	fn sub_ring_vrf_verify(_x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `489`
		//  Estimated: `1869`
		// Minimum execution time: 22_626_151_000 picoseconds.
		Weight::from_parts(23_071_328_218, 1869)
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
	fn ark_ietf_vrf_verify() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_908_103_000 picoseconds.
		Weight::from_parts(2_909_823_000, 0)
	}
	fn sub_ietf_vrf_verify() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 838_706_000 picoseconds.
		Weight::from_parts(839_527_000, 0)
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `ArkVrf::RingKeys` (r:1 w:0)
	/// Proof: `ArkVrf::RingKeys` (`max_values`: Some(1), `max_size`: Some(8162), added: 8657, mode: `MaxEncodedLen`)
	/// Storage: `ArkVrf::RingSize` (r:1 w:1)
	/// Proof: `ArkVrf::RingSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ArkVrf::RingBuilder` (r:1 w:1)
	/// Proof: `ArkVrf::RingBuilder` (`max_values`: Some(1), `max_size`: Some(848), added: 1343, mode: `MaxEncodedLen`)
	/// Storage: `ArkVrf::Srs` (r:7 w:0)
	/// Proof: `ArkVrf::Srs` (`max_values`: None, `max_size`: Some(396), added: 2871, mode: `MaxEncodedLen`)
	/// Storage: `ArkVrf::RingVerifierKey` (r:0 w:1)
	/// Proof: `ArkVrf::RingVerifierKey` (`max_values`: Some(1), `max_size`: Some(384), added: 879, mode: `MaxEncodedLen`)
	/// The range of component `x` is `[1, 50]`.
	fn ark_ring_vrf_commit_buffered(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1808 + x * (87 ±0)`
		//  Estimated: `9647 + x * (355 ±2)`
		// Minimum execution time: 4_894_579_000 picoseconds.
		Weight::from_parts(4_294_985_512, 9647)
			// Standard Error: 4_456_518
			.saturating_add(Weight::from_parts(1_574_884_572, 0).saturating_mul(x.into()))
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 355).saturating_mul(x.into()))
	}
	/// Storage: `ArkVrf::RingKeys` (r:1 w:0)
	/// Proof: `ArkVrf::RingKeys` (`max_values`: Some(1), `max_size`: Some(8162), added: 8657, mode: `MaxEncodedLen`)
	/// Storage: `ArkVrf::RingSize` (r:1 w:1)
	/// Proof: `ArkVrf::RingSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ArkVrf::RingBuilder` (r:1 w:1)
	/// Proof: `ArkVrf::RingBuilder` (`max_values`: Some(1), `max_size`: Some(848), added: 1343, mode: `MaxEncodedLen`)
	/// Storage: `ArkVrf::Srs` (r:7 w:0)
	/// Proof: `ArkVrf::Srs` (`max_values`: None, `max_size`: Some(396), added: 2871, mode: `MaxEncodedLen`)
	/// Storage: `ArkVrf::RingVerifierKey` (r:0 w:1)
	/// Proof: `ArkVrf::RingVerifierKey` (`max_values`: Some(1), `max_size`: Some(384), added: 879, mode: `MaxEncodedLen`)
	/// The range of component `x` is `[1, 50]`.
	fn sub_ring_vrf_commit_buffered(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1808 + x * (87 ±0)`
		//  Estimated: `9647 + x * (355 ±2)`
		// Minimum execution time: 1_325_625_000 picoseconds.
		Weight::from_parts(1_070_210_802, 9647)
			// Standard Error: 319_246
			.saturating_add(Weight::from_parts(459_294_054, 0).saturating_mul(x.into()))
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 355).saturating_mul(x.into()))
	}
	/// Storage: `ArkVrf::RingKeys` (r:1 w:0)
	/// Proof: `ArkVrf::RingKeys` (`max_values`: Some(1), `max_size`: Some(8162), added: 8657, mode: `MaxEncodedLen`)
	/// Storage: `ArkVrf::RingBuilder` (r:1 w:0)
	/// Proof: `ArkVrf::RingBuilder` (`max_values`: Some(1), `max_size`: Some(848), added: 1343, mode: `MaxEncodedLen`)
	/// Storage: `ArkVrf::RingVerifierKey` (r:0 w:1)
	/// Proof: `ArkVrf::RingVerifierKey` (`max_values`: Some(1), `max_size`: Some(384), added: 879, mode: `MaxEncodedLen`)
	/// The range of component `x` is `[1, 50]`.
	fn ark_ring_vrf_commit_unbuffered(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `940`
		//  Estimated: `9647`
		// Minimum execution time: 28_560_000 picoseconds.
		Weight::from_parts(29_212_681, 9647)
			// Standard Error: 724
			.saturating_add(Weight::from_parts(23_986, 0).saturating_mul(x.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `ArkVrf::RingKeys` (r:1 w:0)
	/// Proof: `ArkVrf::RingKeys` (`max_values`: Some(1), `max_size`: Some(8162), added: 8657, mode: `MaxEncodedLen`)
	/// Storage: `ArkVrf::RingBuilder` (r:1 w:0)
	/// Proof: `ArkVrf::RingBuilder` (`max_values`: Some(1), `max_size`: Some(848), added: 1343, mode: `MaxEncodedLen`)
	/// Storage: `ArkVrf::RingVerifierKey` (r:0 w:1)
	/// Proof: `ArkVrf::RingVerifierKey` (`max_values`: Some(1), `max_size`: Some(384), added: 879, mode: `MaxEncodedLen`)
	/// The range of component `x` is `[1, 50]`.
	fn sub_ring_vrf_commit_unbuffered(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `940`
		//  Estimated: `9647`
		// Minimum execution time: 50_911_000 picoseconds.
		Weight::from_parts(51_722_907, 9647)
			// Standard Error: 1_662
			.saturating_add(Weight::from_parts(35_199, 0).saturating_mul(x.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `ArkVrf::RingVerifierKey` (r:1 w:0)
	/// Proof: `ArkVrf::RingVerifierKey` (`max_values`: Some(1), `max_size`: Some(384), added: 879, mode: `MaxEncodedLen`)
	/// The range of component `x` is `[1, 50]`.
	fn ark_ring_vrf_verify(_x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `489`
		//  Estimated: `1869`
		// Minimum execution time: 40_654_535_000 picoseconds.
		Weight::from_parts(41_032_265_431, 1869)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
	}
	/// Storage: `ArkVrf::RingVerifierKey` (r:1 w:0)
	/// Proof: `ArkVrf::RingVerifierKey` (`max_values`: Some(1), `max_size`: Some(384), added: 879, mode: `MaxEncodedLen`)
	/// The range of component `x` is `[1, 50]`.
	fn sub_ring_vrf_verify(_x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `489`
		//  Estimated: `1869`
		// Minimum execution time: 22_626_151_000 picoseconds.
		Weight::from_parts(23_071_328_218, 1869)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
	}
	fn ark_ietf_vrf_verify() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_908_103_000 picoseconds.
		Weight::from_parts(2_909_823_000, 0)
	}
	fn sub_ietf_vrf_verify() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 838_706_000 picoseconds.
		Weight::from_parts(839_527_000, 0)
	}
}
