// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_ark_hostcalls`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2026-01-24, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ggwpez-ref-hw2`, CPU: `AMD EPYC 7232P 8-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// ./target/release/ark-node
// benchmark
// pallet
// --runtime=target/release/wbuild/ark-runtime/ark_runtime.compact.wasm
// --template=pallets/frame-weight-template.hbs
// --pallet
// pallet_ark_hostcalls
// --extrinsic
// *
// --steps
// 50
// --repeat=20
// --no-storage-info
// --disable-proof-recording
// --no-median-slopes
// --json-file=./pallets/hostcalls/src/results.json
// --output=./pallets/hostcalls/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_ark_hostcalls`.
pub trait WeightInfo {
	fn ark_bls12_381_pairing() -> Weight;
	fn sub_bls12_381_pairing() -> Weight;
	fn ark_bls12_381_msm_g1(x: u32, ) -> Weight;
	fn sub_bls12_381_msm_g1(x: u32, ) -> Weight;
	fn ark_bls12_381_mul_projective_g1() -> Weight;
	fn sub_bls12_381_mul_projective_g1() -> Weight;
	fn ark_bls12_381_mul_affine_g1() -> Weight;
	fn sub_bls12_381_mul_affine_g1() -> Weight;
	fn ark_bls12_381_msm_g2(x: u32, ) -> Weight;
	fn sub_bls12_381_msm_g2(x: u32, ) -> Weight;
	fn ark_bls12_381_mul_projective_g2() -> Weight;
	fn sub_bls12_381_mul_projective_g2() -> Weight;
	fn ark_bls12_381_mul_affine_g2() -> Weight;
	fn sub_bls12_381_mul_affine_g2() -> Weight;
	fn ark_ed_on_bls12_377_msm_te(x: u32, ) -> Weight;
	fn sub_ed_on_bls12_377_msm_te(x: u32, ) -> Weight;
	fn ark_ed_on_bls12_377_mul_projective_te() -> Weight;
	fn sub_ed_on_bls12_377_mul_projective_te() -> Weight;
	fn ark_ed_on_bls12_377_mul_affine_te() -> Weight;
	fn sub_ed_on_bls12_377_mul_affine_te() -> Weight;
	fn ark_ed_on_bls12_381_bandersnatch_msm_sw(x: u32, ) -> Weight;
	fn sub_ed_on_bls12_381_bandersnatch_msm_sw(x: u32, ) -> Weight;
	fn ark_ed_on_bls12_381_bandersnatch_mul_projective_sw() -> Weight;
	fn sub_ed_on_bls12_381_bandersnatch_mul_projective_sw() -> Weight;
	fn ark_ed_on_bls12_381_bandersnatch_mul_affine_sw() -> Weight;
	fn sub_ed_on_bls12_381_bandersnatch_mul_affine_sw() -> Weight;
	fn ark_ed_on_bls12_381_bandersnatch_msm_te(x: u32, ) -> Weight;
	fn sub_ed_on_bls12_381_bandersnatch_msm_te(x: u32, ) -> Weight;
	fn ark_ed_on_bls12_381_bandersnatch_mul_projective_te() -> Weight;
	fn sub_ed_on_bls12_381_bandersnatch_mul_projective_te() -> Weight;
	fn ark_ed_on_bls12_381_bandersnatch_mul_affine_te() -> Weight;
	fn sub_ed_on_bls12_381_bandersnatch_mul_affine_te() -> Weight;
}

/// Weights for `pallet_ark_hostcalls` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn ark_bls12_381_pairing() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 10_088_641_000 picoseconds.
		Weight::from_parts(10_099_051_000, 0)
	}
	fn sub_bls12_381_pairing() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_499_075_000 picoseconds.
		Weight::from_parts(2_504_895_000, 0)
	}
	/// The range of component `x` is `[10, 100]`.
	fn ark_bls12_381_msm_g1(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 12_884_898_000 picoseconds.
		Weight::from_parts(5_986_616_193, 0)
			// Standard Error: 2_379_451
			.saturating_add(Weight::from_parts(929_844_025, 0).saturating_mul(x.into()))
	}
	/// The range of component `x` is `[10, 100]`.
	fn sub_bls12_381_msm_g1(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_646_192_000 picoseconds.
		Weight::from_parts(615_304_512, 0)
			// Standard Error: 142_034
			.saturating_add(Weight::from_parts(323_206_096, 0).saturating_mul(x.into()))
	}
	fn ark_bls12_381_mul_projective_g1() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 973_256_000 picoseconds.
		Weight::from_parts(974_596_000, 0)
	}
	fn sub_bls12_381_mul_projective_g1() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 142_531_000 picoseconds.
		Weight::from_parts(148_491_000, 0)
	}
	fn ark_bls12_381_mul_affine_g1() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 1_934_811_000 picoseconds.
		Weight::from_parts(1_938_681_000, 0)
	}
	fn sub_bls12_381_mul_affine_g1() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 1_934_472_000 picoseconds.
		Weight::from_parts(1_938_151_000, 0)
	}
	/// The range of component `x` is `[10, 100]`.
	fn ark_bls12_381_msm_g2(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 32_255_101_000 picoseconds.
		Weight::from_parts(18_180_124_960, 0)
			// Standard Error: 7_085_553
			.saturating_add(Weight::from_parts(2_141_646_162, 0).saturating_mul(x.into()))
	}
	/// The range of component `x` is `[10, 100]`.
	fn sub_bls12_381_msm_g2(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 9_522_987_000 picoseconds.
		Weight::from_parts(1_313_543_996, 0)
			// Standard Error: 297_937
			.saturating_add(Weight::from_parts(852_948_630, 0).saturating_mul(x.into()))
	}
	fn ark_bls12_381_mul_projective_g2() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_647_659_000 picoseconds.
		Weight::from_parts(4_659_000_000, 0)
	}
	fn sub_bls12_381_mul_projective_g2() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 690_905_000 picoseconds.
		Weight::from_parts(696_944_000, 0)
	}
	fn ark_bls12_381_mul_affine_g2() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_197_763_000 picoseconds.
		Weight::from_parts(5_208_333_000, 0)
	}
	fn sub_bls12_381_mul_affine_g2() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_196_493_000 picoseconds.
		Weight::from_parts(5_206_693_000, 0)
	}
	/// The range of component `x` is `[10, 100]`.
	fn ark_ed_on_bls12_377_msm_te(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 12_443_508_000 picoseconds.
		Weight::from_parts(5_027_149_918, 0)
			// Standard Error: 3_111_716
			.saturating_add(Weight::from_parts(930_284_384, 0).saturating_mul(x.into()))
	}
	/// The range of component `x` is `[10, 100]`.
	fn sub_ed_on_bls12_377_msm_te(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_985_429_000 picoseconds.
		Weight::from_parts(479_453_085, 0)
			// Standard Error: 166_190
			.saturating_add(Weight::from_parts(255_170_227, 0).saturating_mul(x.into()))
	}
	fn ark_ed_on_bls12_377_mul_projective_te() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 614_174_000 picoseconds.
		Weight::from_parts(619_943_000, 0)
	}
	fn sub_ed_on_bls12_377_mul_projective_te() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 103_121_000 picoseconds.
		Weight::from_parts(104_171_000, 0)
	}
	fn ark_ed_on_bls12_377_mul_affine_te() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 1_402_989_000 picoseconds.
		Weight::from_parts(1_406_879_000, 0)
	}
	fn sub_ed_on_bls12_377_mul_affine_te() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 370_453_000 picoseconds.
		Weight::from_parts(373_842_000, 0)
	}
	/// The range of component `x` is `[10, 100]`.
	fn ark_ed_on_bls12_381_bandersnatch_msm_sw(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 11_026_159_000 picoseconds.
		Weight::from_parts(2_986_907_027, 0)
			// Standard Error: 1_112_799
			.saturating_add(Weight::from_parts(912_186_460, 0).saturating_mul(x.into()))
	}
	/// The range of component `x` is `[10, 100]`.
	fn sub_ed_on_bls12_381_bandersnatch_msm_sw(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_039_409_000 picoseconds.
		Weight::from_parts(479_249_268, 0)
			// Standard Error: 128_249
			.saturating_add(Weight::from_parts(260_759_215, 0).saturating_mul(x.into()))
	}
	fn ark_ed_on_bls12_381_bandersnatch_mul_projective_sw() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 805_802_000 picoseconds.
		Weight::from_parts(812_501_000, 0)
	}
	fn sub_ed_on_bls12_381_bandersnatch_mul_projective_sw() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 148_432_000 picoseconds.
		Weight::from_parts(149_762_000, 0)
	}
	fn ark_ed_on_bls12_381_bandersnatch_mul_affine_sw() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 1_483_811_000 picoseconds.
		Weight::from_parts(1_489_092_000, 0)
	}
	fn sub_ed_on_bls12_381_bandersnatch_mul_affine_sw() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 402_685_000 picoseconds.
		Weight::from_parts(408_656_000, 0)
	}
	/// The range of component `x` is `[10, 100]`.
	fn ark_ed_on_bls12_381_bandersnatch_msm_te(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 12_033_422_000 picoseconds.
		Weight::from_parts(5_088_349_647, 0)
			// Standard Error: 3_222_895
			.saturating_add(Weight::from_parts(895_491_059, 0).saturating_mul(x.into()))
	}
	/// The range of component `x` is `[10, 100]`.
	fn sub_ed_on_bls12_381_bandersnatch_msm_te(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_710_625_000 picoseconds.
		Weight::from_parts(513_600_604, 0)
			// Standard Error: 166_970
			.saturating_add(Weight::from_parts(233_261_877, 0).saturating_mul(x.into()))
	}
	fn ark_ed_on_bls12_381_bandersnatch_mul_projective_te() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 613_578_000 picoseconds.
		Weight::from_parts(621_048_000, 0)
	}
	fn sub_ed_on_bls12_381_bandersnatch_mul_projective_te() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 109_721_000 picoseconds.
		Weight::from_parts(110_591_000, 0)
	}
	fn ark_ed_on_bls12_381_bandersnatch_mul_affine_te() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 1_329_407_000 picoseconds.
		Weight::from_parts(1_336_746_000, 0)
	}
	fn sub_ed_on_bls12_381_bandersnatch_mul_affine_te() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 318_624_000 picoseconds.
		Weight::from_parts(322_934_000, 0)
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	fn ark_bls12_381_pairing() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 10_088_641_000 picoseconds.
		Weight::from_parts(10_099_051_000, 0)
	}
	fn sub_bls12_381_pairing() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_499_075_000 picoseconds.
		Weight::from_parts(2_504_895_000, 0)
	}
	/// The range of component `x` is `[10, 100]`.
	fn ark_bls12_381_msm_g1(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 12_884_898_000 picoseconds.
		Weight::from_parts(5_986_616_193, 0)
			// Standard Error: 2_379_451
			.saturating_add(Weight::from_parts(929_844_025, 0).saturating_mul(x.into()))
	}
	/// The range of component `x` is `[10, 100]`.
	fn sub_bls12_381_msm_g1(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_646_192_000 picoseconds.
		Weight::from_parts(615_304_512, 0)
			// Standard Error: 142_034
			.saturating_add(Weight::from_parts(323_206_096, 0).saturating_mul(x.into()))
	}
	fn ark_bls12_381_mul_projective_g1() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 973_256_000 picoseconds.
		Weight::from_parts(974_596_000, 0)
	}
	fn sub_bls12_381_mul_projective_g1() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 142_531_000 picoseconds.
		Weight::from_parts(148_491_000, 0)
	}
	fn ark_bls12_381_mul_affine_g1() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 1_934_811_000 picoseconds.
		Weight::from_parts(1_938_681_000, 0)
	}
	fn sub_bls12_381_mul_affine_g1() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 1_934_472_000 picoseconds.
		Weight::from_parts(1_938_151_000, 0)
	}
	/// The range of component `x` is `[10, 100]`.
	fn ark_bls12_381_msm_g2(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 32_255_101_000 picoseconds.
		Weight::from_parts(18_180_124_960, 0)
			// Standard Error: 7_085_553
			.saturating_add(Weight::from_parts(2_141_646_162, 0).saturating_mul(x.into()))
	}
	/// The range of component `x` is `[10, 100]`.
	fn sub_bls12_381_msm_g2(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 9_522_987_000 picoseconds.
		Weight::from_parts(1_313_543_996, 0)
			// Standard Error: 297_937
			.saturating_add(Weight::from_parts(852_948_630, 0).saturating_mul(x.into()))
	}
	fn ark_bls12_381_mul_projective_g2() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_647_659_000 picoseconds.
		Weight::from_parts(4_659_000_000, 0)
	}
	fn sub_bls12_381_mul_projective_g2() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 690_905_000 picoseconds.
		Weight::from_parts(696_944_000, 0)
	}
	fn ark_bls12_381_mul_affine_g2() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_197_763_000 picoseconds.
		Weight::from_parts(5_208_333_000, 0)
	}
	fn sub_bls12_381_mul_affine_g2() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_196_493_000 picoseconds.
		Weight::from_parts(5_206_693_000, 0)
	}
	/// The range of component `x` is `[10, 100]`.
	fn ark_ed_on_bls12_377_msm_te(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 12_443_508_000 picoseconds.
		Weight::from_parts(5_027_149_918, 0)
			// Standard Error: 3_111_716
			.saturating_add(Weight::from_parts(930_284_384, 0).saturating_mul(x.into()))
	}
	/// The range of component `x` is `[10, 100]`.
	fn sub_ed_on_bls12_377_msm_te(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_985_429_000 picoseconds.
		Weight::from_parts(479_453_085, 0)
			// Standard Error: 166_190
			.saturating_add(Weight::from_parts(255_170_227, 0).saturating_mul(x.into()))
	}
	fn ark_ed_on_bls12_377_mul_projective_te() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 614_174_000 picoseconds.
		Weight::from_parts(619_943_000, 0)
	}
	fn sub_ed_on_bls12_377_mul_projective_te() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 103_121_000 picoseconds.
		Weight::from_parts(104_171_000, 0)
	}
	fn ark_ed_on_bls12_377_mul_affine_te() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 1_402_989_000 picoseconds.
		Weight::from_parts(1_406_879_000, 0)
	}
	fn sub_ed_on_bls12_377_mul_affine_te() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 370_453_000 picoseconds.
		Weight::from_parts(373_842_000, 0)
	}
	/// The range of component `x` is `[10, 100]`.
	fn ark_ed_on_bls12_381_bandersnatch_msm_sw(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 11_026_159_000 picoseconds.
		Weight::from_parts(2_986_907_027, 0)
			// Standard Error: 1_112_799
			.saturating_add(Weight::from_parts(912_186_460, 0).saturating_mul(x.into()))
	}
	/// The range of component `x` is `[10, 100]`.
	fn sub_ed_on_bls12_381_bandersnatch_msm_sw(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_039_409_000 picoseconds.
		Weight::from_parts(479_249_268, 0)
			// Standard Error: 128_249
			.saturating_add(Weight::from_parts(260_759_215, 0).saturating_mul(x.into()))
	}
	fn ark_ed_on_bls12_381_bandersnatch_mul_projective_sw() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 805_802_000 picoseconds.
		Weight::from_parts(812_501_000, 0)
	}
	fn sub_ed_on_bls12_381_bandersnatch_mul_projective_sw() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 148_432_000 picoseconds.
		Weight::from_parts(149_762_000, 0)
	}
	fn ark_ed_on_bls12_381_bandersnatch_mul_affine_sw() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 1_483_811_000 picoseconds.
		Weight::from_parts(1_489_092_000, 0)
	}
	fn sub_ed_on_bls12_381_bandersnatch_mul_affine_sw() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 402_685_000 picoseconds.
		Weight::from_parts(408_656_000, 0)
	}
	/// The range of component `x` is `[10, 100]`.
	fn ark_ed_on_bls12_381_bandersnatch_msm_te(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 12_033_422_000 picoseconds.
		Weight::from_parts(5_088_349_647, 0)
			// Standard Error: 3_222_895
			.saturating_add(Weight::from_parts(895_491_059, 0).saturating_mul(x.into()))
	}
	/// The range of component `x` is `[10, 100]`.
	fn sub_ed_on_bls12_381_bandersnatch_msm_te(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_710_625_000 picoseconds.
		Weight::from_parts(513_600_604, 0)
			// Standard Error: 166_970
			.saturating_add(Weight::from_parts(233_261_877, 0).saturating_mul(x.into()))
	}
	fn ark_ed_on_bls12_381_bandersnatch_mul_projective_te() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 613_578_000 picoseconds.
		Weight::from_parts(621_048_000, 0)
	}
	fn sub_ed_on_bls12_381_bandersnatch_mul_projective_te() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 109_721_000 picoseconds.
		Weight::from_parts(110_591_000, 0)
	}
	fn ark_ed_on_bls12_381_bandersnatch_mul_affine_te() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 1_329_407_000 picoseconds.
		Weight::from_parts(1_336_746_000, 0)
	}
	fn sub_ed_on_bls12_381_bandersnatch_mul_affine_te() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 318_624_000 picoseconds.
		Weight::from_parts(322_934_000, 0)
	}
}
